tasks:
  campaign_review:
    description: "\n            Analyze the marketing campaign 'Eco Friendly Spring\
      \ Launch' by GreenLeaf Products for their product 'GreenLife Reusable Bottles'.\n\
      \            The campaign is targeted at 18-25 audiences in North America with\
      \ interests in Eco-friendly lifestyle, sustainable products, health and wellness.\n\
      \            \n            As an agent with your backstory, your review should\
      \ reflect your unique perspective. \n            Please make sure to evaluate\
      \ the campaign from the angle of your backstory and role without introducing\
      \ general assumptions.\n            \n            **Campaign Overview:**\n \
      \           - **Campaign Name**: Eco Friendly Spring Launch\n            - **Company**:\
      \ GreenLeaf Products\n            - **Campaign Description**: Promoting eco-friendly\
      \ products for spring 2025. Focuses on sustainability, natural ingredients,\
      \ and recyclable packaging.\n            \n            **Product Details:**\n\
      \            - **Product Name**: GreenLife Reusable Bottles\n            - **Product\
      \ Description**: Reusable bottles made from recycled materials, available in\
      \ eco-friendly packaging.\n            \n            **Target Audience:**\n\
      \            - **Age Group**: 18-25\n            - **Location**: North America\n\
      \            - **Interests**: Eco-friendly lifestyle, sustainable products,\
      \ health and wellness\n            - **Income Bracket**: Middle\n          \
      \  \n            Your role requires you to assess this campaign based on how\
      \ it resonates with the target audience from your unique perspective. \n   \
      \         Please analyze this campaign's strengths, weaknesses, appeal, and\
      \ engagement through the lens of your personal backstory and role.\n       \
      \     "
    expected_output: "\n            Provide a structured markdown report following\
      \ this format(please dont change the format of the report that your produce\
      \ and follow this):\n\n            - **Score**: Provide a score (out of 10)\
      \ based on the campaign\u2019s effectiveness and alignment with the target audience.\n\
      \            - **Campaign Strengths**: Identify aspects of the campaign that\
      \ align well with your perspective and the target audience.\n            - **Campaign\
      \ Weaknesses**: Highlight any gaps or shortcomings that are apparent from your\
      \ expertise and experience.\n            - **Appeal and Engagement**: Evaluate\
      \ how engaging the campaign is, considering the target audience's interests\
      \ and your viewpoint.\n            - **Recommendations for Improvement**: Offer\
      \ actionable suggestions for enhancing the campaign, drawing from your own professional\
      \ background.\n            \n            Please use only the provided campaign\
      \ details and any images and PDFs(if available) to guide your review. Your analysis\
      \ should be thoughtful, concise, and based on your specific perspective.\n \
      \           "
